name: main
on:
   push:
      branches:
        - main
permissions:
   contents: write
jobs:
   deploy:
      runs-on: ubuntu-latest
      steps:
        - users: actions/checkout@v3
        - users: actions/setup-python@v4
          with:
             python-version: 3.x
        - users: action/cache@v2
          with:
             key: ${{ github.ref }}
             path: .cache
        - run: pip install mkdocs-material
        - run: mkdocs gh-deploy --force
        - run: mkdocs --version
